Repository benedekhalaj/terraforming-mars-forum-api, pull requests merged in 2022-09, with the labels that each got.

#149 Angular comment design
  angular/src/app/app.module.ts
  angular/src/app/components/comment/comment.component.css
  angular/src/app/components/comment/comment.component.html
  angular/src/app/components/comment/comment.component.ts
  angular/src/app/components/user-post-components/user-post-actions-menu/user-post-actions-menu.component.css
  angular/src/app/components/user-post-components/user-post-actions-menu/user-post-actions-menu.component.html
  angular/src/app/components/user-post-components/user-post-actions-menu/user-post-actions-menu.component.spec.ts
  angular/src/app/components/user-post-components/user-post-actions-menu/user-post-actions-menu.component.ts
  angular/src/app/components/user-post-components/user-post-detail/user-post-detail.component.css
  angular/src/app/components/user-post-components/user-post-detail/user-post-detail.component.html
  angular/src/app/components/user-post-components/user-post/user-post.component.css
  angular/src/app/components/user-post-components/user-post/user-post.component.html
  angular/src/app/components/user-post-components/user-post/user-post.component.ts
Labels: task

#151 Header and footer material design
  angular/src/app/app.component.html
  angular/src/app/app.module.ts
  angular/src/app/components/footer/footer.component.css
  angular/src/app/components/header/header.component.html
  angular/src/app/components/navigation-bar/navigation-bar.component.css
  angular/src/app/components/navigation-bar/navigation-bar.component.html
  angular/src/styles.css
Labels: task

#192 Enable cors
  angular/angular.json
  angular/src/app/app.module.ts
  angular/src/app/services/comment/comment.service.ts
  angular/src/app/services/in-memory-data.service.spec.ts
  angular/src/app/services/in-memory-data.service.ts
  angular/src/app/services/league-post-detail/league-post-detail.service.ts
  angular/src/app/services/league-post/league-post.service.ts
  angular/src/app/services/registration/registration.service.ts
  angular/src/app/services/user/user.service.ts
  angular/src/environments/environment.ts
  angular/src/proxy.conf.json
Labels: spike, angular

#215 Unique username and email of AppUser
  springboot/src/main/java/com/codecool/terraformingmarsforum/model/AppUser.java
Labels: database
